//dictionary to decode rexponse from server
const chainIdToNameMap = {
  LAV1: "Lava MainNet",
  ETH1: "Ethereum Mainnet",
  COS5: "Cosmos Hub Mainnet",
  POLYGON1: "Polygon Mainnet",
  COS3: "Osmosis Mainnet",
  FTM250: "Fantom Mainnet",
  CELO: "Celo Mainnet",
  ARB1: "Arbitrum Mainnet",
  APT1: "Aptos Mainnet",
  STRK: "Starknet Mainnet",
  EVMOS: "Evmos Mainnet",
  OPTM: "Optimism Mainnet",
  CANTO: "Canto Mainnet",
  AVAX: "Avalanche Mainnet",
  SOLANA: "Solana Mainnet",
  FVM: "Filecoin Mainnet",
  JUN1: "Juno Mainnet",
  LAV1T: "Lava Testnet",
  GTH1: "Ethereum Testnet",
  COS5T: "Cosmos Hub Testnet",
  JUNT1: "Juno Testnet",
  POLYGON1T: "Polygon Testnet",
  COS4: "Osmosis Testnet",
  FTM250T: "Fantom Testnet",
  ALFAJORES: "Celo Testnet",
  ARB1T: "Arbitrum Testnet",
  APT1T: "Aptos Testnet",
  STRKT: "Starknet Testnet",
  EVMOST: "Evmos Testnet",
  BASET: "Base Testnet",
  OPTMT: "Optimism Testnet",
  CANTOT: "Canto Testnet",
  AVAXT: "Avalanche Testnet",
  SOLANAT: "Solana Testnet",
  FVMT: "Filecoin Testnet",
};

export default chainIdToNameMap;
